# ci.yml file for GitHub Actions
name: Documentation

on:
  push:
    branches:
      - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build_docs:
    runs-on: windows-latest
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        
      - name: Setup Node.js
        uses: actions/setup-node@v2
        
      - name: Install dependencies
        run: npm ci
        working-directory: ./client

      - name: Create the docs directory locally in CI
        run: npx typedoc --out ../docs/client @types/*.d.ts src/**/*.ts
        working-directory: ./client

      - name: Install Doxygen
        uses: ssciwr/doxygen-install@v1

      - name: Generate Doxygen Documentation
        run: doxygen docs
        working-directory: ./src
        
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
